apiVersion: v1
data:
  username: bWlzc2tleQ==
  password: RVFkdTl6b1I2aGNaQ28=
kind: Secret
metadata:
  name: misskey-local-user-secret
type: kubernetes.io/basic-auth
---

apiVersion: v1
data:
  password: dU4zaTFIaDBiWWJDYzRUeVZBYWNCaG1TemdxdHpxeG1PVmpBbjBRSUNoc0pyU211OVBZMmZ3MnE4RUtLTHBaOQ==
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: pg-admin-secret
type: kubernetes.io/basic-auth
---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shahu-pg-cluster
  namespace: shahu-ski
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  minSyncReplicas: 1
  maxSyncReplicas: 2
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: rook-ceph-block
      resources:
        requests:
          storage: 70Gi

  # pg設定
  postgresql:
    parameters:
      max_connections: "128"
      shared_buffers: "4GB"
      effective_cache_size: "6GB"
      maintenance_work_mem: "512MB"
      checkpoint_completion_target: "0.7"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "300"
      work_mem: "1GB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      max_worker_processes: "4"
      max_parallel_workers_per_gather: "2"
      max_parallel_workers: "4"
      max_parallel_maintenance_workers: "2"

  superuserSecret: 
    name: pg-admin-secret

  # 起動時の設定
  bootstrap:
    initdb:
      database: mk1
      owner: misskey
      secret:
        name: misskey-local-user-secret # 上記ownerのパスワードについて。kubernetesの公式を参照
