apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: shahu-ski
spec:
  selector:
    app: redis
  ports:
  - name: http
    port: 6379

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shahu-redis-pvc
  namespace: shahu-ski
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: shahu-ski
  labels:
    app: redis
spec:
  restartPolicy: Always
  containers:
  - name: redis
    image: redis:7
    volumeMounts:
    - mountPath: /data
      name: redis-volume
    ports:
    - containerPort: 6379
  volumes:
  - name: redis-volume
    persistentVolumeClaim:
      claimName: shahu-redis-pvc
